#!/bin/bash
set -eou pipefail

if [ $# -le 1 ]; then
    echo -e "Usage: \n$0 <channel> <coreos version>"
    exit 1
fi

CHANNEL=$1
VERSION=$2

rm -rf assets
${PWD}/coreos-baremetal/scripts/get-coreos ${CHANNEL} ${VERSION} ${PWD}/assets
docker build --build-arg VERSION=${VERSION} -t kubermesh/coreos-images:${VERSION} .
docker push kubermesh/coreos-images:${VERSION}
